# Generated by Django 5.1.7 on 2026-07-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_id_alter_order_id_alter_phone_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='shop_mechta_url',
            field=models.URLField(blank=True, default='', verbose_name='Mechta'),
        ),
        migrations.AddField(
            model_name='phone',
            name='shop_sulpak_url',
            field=models.URLField(blank=True, default='', verbose_name='Sulpak'),
        ),
        migrations.AddField(
            model_name='phone',
            name='shop_technodom_url',
            field=models.URLField(blank=True, default='', verbose_name='Technodom'),
        ),
    ]
