PHONE_DETAIL_CONTENT = {
    "Samsung Galaxy A56 5G 128GB Awesome Lightgray (SM-A566) EZAAS": {
        "tagline": "Тонкий средний класс Samsung с ярким AMOLED, защитой IP67 и долгой поддержкой.",
        "color": "Awesome Lightgray",
        "storage": "128 GB",
        "memory": "8 GB RAM",
        "overview": "Galaxy A56 5G делает упор на сбалансированный опыт: большой 6.7-дюймовый Super AMOLED экран 120 Гц, камера 50 МП с OIS, батарея 5000 мАч и быстрая зарядка до 45 Вт. Это хороший выбор для повседневной работы, фото, видео и долгого срока службы.",
        "highlights": ["6.7\" Super AMOLED 120 Гц", "Exynos 1580", "50 МП OIS + 12 МП ultra-wide", "5000 мАч, зарядка 45 Вт", "IP67"],
        "specs": [
            ("Экран", "6.7\" FHD+ Super AMOLED, 120 Гц"),
            ("Процессор", "Samsung Exynos 1580"),
            ("Память", "8 GB RAM / 128 GB"),
            ("Камеры", "50 МП OIS + 12 МП ultra-wide + 5 МП macro, фронтальная 12 МП"),
            ("Батарея", "5000 мАч, быстрая зарядка до 45 Вт"),
            ("Защита", "IP67, Gorilla Glass Victus+"),
        ],
    },
    "HONOR 600 Pro (12/512GB) Orange": {
        "tagline": "Флагманский HONOR с мощным чипом, 200 МП камерой и большой батареей.",
        "color": "Orange",
        "storage": "512 GB",
        "memory": "12 GB RAM",
        "overview": "HONOR 600 Pro рассчитан на тех, кому важны камера, автономность и производительность. У модели AMOLED-дисплей до 120 Гц, Snapdragon 8 Elite, основная камера 200 МП и батарея большой емкости с быстрой зарядкой.",
        "highlights": ["AMOLED 120 Гц", "Snapdragon 8 Elite", "200 МП основная камера", "50 МП селфи-камера", "Быстрая зарядка 80 Вт"],
        "specs": [
            ("Экран", "6.57\" AMOLED, 120 Гц"),
            ("Процессор", "Qualcomm Snapdragon 8 Elite"),
            ("Память", "12 GB RAM / 512 GB"),
            ("Камеры", "200 МП main + 12 МП ultra-wide + telephoto, фронтальная 50 МП"),
            ("Батарея", "Около 6400 мАч, проводная зарядка 80 Вт"),
            ("Система", "Android / MagicOS"),
        ],
    },
    "APPLE iPhone 17 Pro Max 256GB (Silver)": {
        "tagline": "Самый крупный Pro iPhone с A19 Pro, 6.9\" OLED и лучшей батареей линейки.",
        "color": "Silver",
        "storage": "256 GB",
        "memory": "12 GB RAM",
        "overview": "iPhone 17 Pro Max сочетает 6.9-дюймовый Super Retina XDR OLED, чип A19 Pro, систему из трех 48 МП камер и увеличенное время работы. Модель подходит для съемки, игр, монтажа видео и долгой работы без подзарядки.",
        "highlights": ["6.9\" Super Retina XDR", "Apple A19 Pro", "Три 48 МП камеры", "До 39 часов видео", "IP68"],
        "specs": [
            ("Экран", "6.9\" OLED, 2868 x 1320, ProMotion до 120 Гц"),
            ("Процессор", "Apple A19 Pro"),
            ("Память", "256 GB"),
            ("Камеры", "48 МП Fusion Main + 48 МП Ultra Wide + 48 МП Telephoto, фронтальная 18 МП Center Stage"),
            ("Батарея", "До 39 часов воспроизведения видео"),
            ("Система", "iOS 26"),
        ],
    },
    "Apple iPhone 16 128GB (Pink)": {
        "tagline": "Компактный iPhone с A18, Camera Control и ярким корпусом.",
        "color": "Pink",
        "storage": "128 GB",
        "memory": "8 GB RAM",
        "overview": "iPhone 16 получил чип A18, обновленную 48 МП Fusion-камеру, поддержку Apple Intelligence и отдельную кнопку Camera Control. Это базовая модель, но с хорошим запасом производительности.",
        "highlights": ["6.1\" Super Retina XDR", "Apple A18", "48 МП Fusion camera", "Camera Control", "IP68"],
        "specs": [
            ("Экран", "6.1\" Super Retina XDR OLED"),
            ("Процессор", "Apple A18"),
            ("Память", "128 GB"),
            ("Камеры", "48 МП Fusion + 12 МП ultra-wide, фронтальная 12 МП"),
            ("Связь", "5G, Wi-Fi 7, Bluetooth 5.3, USB-C"),
            ("Защита", "IP68"),
        ],
    },
    "APPLE iPhone 17 Pro 256GB (Silver)": {
        "tagline": "Pro-возможности iPhone 17 в более компактном корпусе.",
        "color": "Silver",
        "storage": "256 GB",
        "memory": "12 GB RAM",
        "overview": "iPhone 17 Pro предлагает A19 Pro, 6.3-дюймовый OLED ProMotion, профессиональную систему камер и новые возможности съемки. Он ближе к Pro Max по характеристикам, но удобнее для одной руки.",
        "highlights": ["6.3\" OLED ProMotion", "Apple A19 Pro", "48 МП Pro camera system", "18 МП Center Stage", "IP68"],
        "specs": [
            ("Экран", "6.3\" OLED, 2622 x 1206, ProMotion до 120 Гц"),
            ("Процессор", "Apple A19 Pro"),
            ("Память", "256 GB"),
            ("Камеры", "48 МП Fusion Main + 48 МП Ultra Wide + 48 МП Telephoto"),
            ("Селфи", "18 МП Center Stage"),
            ("Связь", "5G, Wi-Fi 7, Bluetooth 6"),
        ],
    },
    "HONOR 600 (8/256GB) Orange": {
        "tagline": "Яркий HONOR с большим запасом памяти, сильной камерой и быстрой зарядкой.",
        "color": "Orange",
        "storage": "256 GB",
        "memory": "8 GB RAM",
        "overview": "HONOR 600 ориентирован на повседневный комфорт: плавный OLED-дисплей, 200 МП основная камера, 50 МП фронтальная камера и емкая батарея. Хороший вариант, если нужен свежий смартфон без флагманской цены.",
        "highlights": ["OLED 120 Гц", "200 МП камера", "50 МП фронтальная", "Большая батарея", "Быстрая зарядка"],
        "specs": [
            ("Экран", "OLED, до 120 Гц"),
            ("Память", "8 GB RAM / 256 GB"),
            ("Камеры", "200 МП main, фронтальная 50 МП"),
            ("Батарея", "Емкая батарея с быстрой зарядкой"),
            ("Система", "Android / MagicOS"),
            ("Цвет", "Orange"),
        ],
    },
    "Apple iPhone 15 128GB (Pink)": {
        "tagline": "iPhone с Dynamic Island, USB-C и надежной 48 МП камерой.",
        "color": "Pink",
        "storage": "128 GB",
        "memory": "6 GB RAM",
        "overview": "iPhone 15 остается сильной базовой моделью: 6.1-дюймовый Super Retina XDR OLED, чип A16 Bionic, Dynamic Island и 48 МП основная камера. USB-C делает его удобнее для зарядки и аксессуаров.",
        "highlights": ["6.1\" Super Retina XDR", "Apple A16 Bionic", "Dynamic Island", "48 МП main camera", "USB-C"],
        "specs": [
            ("Экран", "6.1\" OLED, 2556 x 1179"),
            ("Процессор", "Apple A16 Bionic"),
            ("Память", "128 GB"),
            ("Камеры", "48 МП main + 12 МП ultra-wide, фронтальная 12 МП"),
            ("Связь", "5G, Wi-Fi 6, Bluetooth 5.3, USB-C"),
            ("Защита", "IP68"),
        ],
    },
    "APPLE iPhone 17 Pro Max 2TB (Cosmic Orange)": {
        "tagline": "Максимальная версия iPhone 17 Pro Max с 2 TB для видео и проектов.",
        "color": "Cosmic Orange",
        "storage": "2 TB",
        "memory": "12 GB RAM",
        "overview": "Эта конфигурация iPhone 17 Pro Max рассчитана на тех, кто снимает много фото и видео, хранит проекты локально и хочет максимум памяти. В остальном это тот же крупный Pro Max с A19 Pro, 6.9\" OLED и тройной 48 МП камерой.",
        "highlights": ["2 TB storage", "6.9\" Super Retina XDR", "Apple A19 Pro", "Три 48 МП камеры", "До 39 часов видео"],
        "specs": [
            ("Экран", "6.9\" OLED, 2868 x 1320, ProMotion до 120 Гц"),
            ("Процессор", "Apple A19 Pro"),
            ("Память", "2 TB"),
            ("Камеры", "48 МП Fusion Main + 48 МП Ultra Wide + 48 МП Telephoto"),
            ("Селфи", "18 МП Center Stage"),
            ("Система", "iOS 26"),
        ],
    },
    "Apple iPhone 15 128GB (Black)": {
        "tagline": "Классический черный iPhone 15 с OLED, Dynamic Island и USB-C.",
        "color": "Black",
        "storage": "128 GB",
        "memory": "6 GB RAM",
        "overview": "iPhone 15 в черном цвете предлагает ту же основу: яркий OLED-дисплей, A16 Bionic, Dynamic Island, USB-C и 48 МП камеру для повседневной съемки.",
        "highlights": ["6.1\" Super Retina XDR", "Apple A16 Bionic", "Dynamic Island", "48 МП camera", "IP68"],
        "specs": [
            ("Экран", "6.1\" OLED, 2556 x 1179"),
            ("Процессор", "Apple A16 Bionic"),
            ("Память", "128 GB"),
            ("Камеры", "48 МП main + 12 МП ultra-wide, фронтальная 12 МП"),
            ("Связь", "5G, Wi-Fi 6, Bluetooth 5.3"),
            ("Корпус", "Aluminum + color-infused glass"),
        ],
    },
    "Xiaomi Redmi Note 13 Pro+ 5G 12/512GB Midnight Black": {
        "tagline": "Redmi с 200 МП камерой, AMOLED 120 Гц и очень быстрой зарядкой.",
        "color": "Midnight Black",
        "storage": "512 GB",
        "memory": "12 GB RAM",
        "overview": "Redmi Note 13 Pro+ 5G выделяется 200 МП основной камерой с OIS, 6.67-дюймовым AMOLED 120 Гц, защитой IP68 и зарядкой 120 Вт. Это сильная модель среднего сегмента для фото, игр и мультимедиа.",
        "highlights": ["6.67\" AMOLED 120 Гц", "Dimensity 7200-Ultra", "200 МП OIS", "5000 мАч", "120 Вт"],
        "specs": [
            ("Экран", "6.67\" AMOLED, 120 Гц, HDR10+ / Dolby Vision"),
            ("Процессор", "MediaTek Dimensity 7200-Ultra"),
            ("Память", "12 GB RAM / 512 GB"),
            ("Камеры", "200 МП OIS + 8 МП ultra-wide + 2 МП macro"),
            ("Батарея", "5000 мАч, зарядка 120 Вт"),
            ("Защита", "IP68"),
        ],
    },
    "Samsung Galaxy A26 5G 256GB White (SM-A266) BZWHS": {
        "tagline": "Доступный Samsung 5G с AMOLED 120 Гц, IP67 и microSD.",
        "color": "White",
        "storage": "256 GB",
        "memory": "8 GB RAM",
        "overview": "Galaxy A26 5G закрывает базовые задачи с запасом: большой Super AMOLED экран 120 Гц, батарея 5000 мАч, камера 50 МП с OIS и защита IP67. Поддержка microSD делает модель удобной для хранения фото и видео.",
        "highlights": ["6.7\" Super AMOLED 120 Гц", "Exynos 1380", "50 МП OIS", "5000 мАч", "microSD"],
        "specs": [
            ("Экран", "6.7\" Super AMOLED, 120 Гц"),
            ("Процессор", "Samsung Exynos 1380"),
            ("Память", "8 GB RAM / 256 GB, microSD"),
            ("Камеры", "50 МП OIS + 8 МП ultra-wide + 2 МП macro, фронтальная 13 МП"),
            ("Батарея", "5000 мАч, зарядка 25 Вт"),
            ("Защита", "IP67"),
        ],
    },
    "OPPO A6 (8/256) Aurora Gold": {
        "tagline": "Недорогой OPPO с 8 GB RAM, большим хранилищем и золотистым корпусом.",
        "color": "Aurora Gold",
        "storage": "256 GB",
        "memory": "8 GB RAM",
        "overview": "OPPO A6 подойдет как практичный смартфон на каждый день: 8 GB оперативной памяти, большой накопитель, IPS-экран и аккуратный золотистый корпус. В каталоге Mechta эта конфигурация указана как 8/256.",
        "highlights": ["IPS display", "8 GB RAM", "256 GB storage", "Aurora Gold", "12 месяцев гарантии"],
        "specs": [
            ("Экран", "IPS"),
            ("Память", "8 GB RAM / 256 GB"),
            ("Бренд", "OPPO"),
            ("Модель", "OPPO A6"),
            ("Цвет", "Aurora Gold"),
            ("Гарантия", "12 месяцев"),
        ],
    },
}

def get_phone_detail_content(phone):
    return PHONE_DETAIL_CONTENT.get(phone.name)
